package desc

const (
	ChapterHelloTriangleSub1  = "1.1.hello_window"
	ChapterHelloTriangleSub2  = "1.2.hello_window_clear"
	ChapterHelloTriangleSub3  = "2.1.hello_triangle"
	ChapterHelloTriangleSub4  = "2.2.hello_triangle_indexed"
	ChapterHelloTriangleSub5  = "2.3.hello_triangle_exercise1"
	ChapterHelloTriangleSub6  = "2.4.hello_triangle_exercise2"
	ChapterHelloTriangleSub7  = "2.5.hello_triangle_exercise3"
	ChapterHelloTriangleSub8  = "3.1.shaders_uniform"
	ChapterHelloTriangleSub9  = "3.2.shaders_interpolation"
	ChapterHelloTriangleSub10 = "3.3.shaders_class"
	ChapterHelloTriangleSub11 = "3.4.shaders_exercise1"
	ChapterHelloTriangleSub12 = "3.5.shaders_exercise2"
	ChapterHelloTriangleSub13 = "3.6.shaders_exercise3"
	ChapterHelloTriangleSub14 = "4.1.textures"
	ChapterHelloTriangleSub15 = "4.2.textures_combined"
	ChapterHelloTriangleSub16 = "4.3.textures_exercise1"
	ChapterHelloTriangleSub17 = "4.4.textures_exercise2"
	ChapterHelloTriangleSub18 = "4.5.textures_exercise3"
	ChapterHelloTriangleSub19 = "4.6.textures_exercise4"
	ChapterHelloTriangleSub20 = "5.1.transformations"
	ChapterHelloTriangleSub21 = "5.2.transformations_exercise1"
	ChapterHelloTriangleSub22 = "5.2.transformations_exercise2"
	ChapterHelloTriangleSub23 = "6.1.coordinate_systems"
	ChapterHelloTriangleSub24 = "6.2.coordinate_systems_depth"
	ChapterHelloTriangleSub25 = "6.3.coordinate_systems_multiple"
	ChapterHelloTriangleSub26 = "6.4.coordinate_systems_exercise3"
	ChapterHelloTriangleSub27 = ".1.camera_circle"
	ChapterHelloTriangleSub28 = "7.2.camera_keyboard_dt"
	ChapterHelloTriangleSub29 = "7.3.camera_mouse_zoom"
	ChapterHelloTriangleSub30 = "7.4.camera_class"
	ChapterHelloTriangleSub31 = "7.5.camera_exercise1"
	ChapterHelloTriangleSub32 = "7.6.camera_exercise2"
)

const (
	ChapterLighting1 = "1.colors"
ChapterLighting2 = "2.1.basic_lighting_diffuse"
ChapterLighting3 = "2.2.basic_lighting_specular"
ChapterLighting4 = "2.3.basic_lighting_exercise1"
ChapterLighting5 = "2.4.basic_lighting_exercise2"
ChapterLighting6 = "2.5.basic_lighting_exercise3"
ChapterLighting7 = "3.1.materials"
ChapterLighting8 = "3.2.materials_exercise1"
ChapterLighting9 = "4.1.lighting_maps_diffuse_map"
ChapterLighting10 = "4.2.lighting_maps_specular_map"
ChapterLighting11 = "4.3.lighting_maps_exercise2"
ChapterLighting12 = "4.4.lighting_maps_exercise4"
ChapterLighting13 = "5.1.light_casters_directional"
ChapterLighting14 = "5.2.light_casters_point"
ChapterLighting15 = "5.3.light_casters_spot"
ChapterLighting16 = "5.4.light_casters_spot_soft"
ChapterLighting17 = "6.multiple_lights"
ChapterLighting18 = "6.multiple_lights_exercise1"
)

const (
	ChapterModelLoading1 = "1.model_loading"
)
const (
	ChapterAdvancedOpengl1 = "1.1.depth_testing"
ChapterAdvancedOpengl2 = "1.2.depth_testing_view"
ChapterAdvancedOpengl3 = "10.1.instancing_quads"
ChapterAdvancedOpengl4 = "10.2.asteroids"
ChapterAdvancedOpengl5 = "10.3.asteroids_instanced"
ChapterAdvancedOpengl6 = "11.1.anti_aliasing_msaa"
ChapterAdvancedOpengl7 = "11.2.anti_aliasing_offscreen"
ChapterAdvancedOpengl8 = "2.stencil_testing"
ChapterAdvancedOpengl9 = "3.1.blending_discard"
ChapterAdvancedOpengl10 = "3.2.blending_sort"
ChapterAdvancedOpengl11 = "4.face_culling_exercise1"
ChapterAdvancedOpengl12 = "5.1.framebuffers"
ChapterAdvancedOpengl13 = "5.2.framebuffers_exercise1"
ChapterAdvancedOpengl14 = "6.1.cubemaps_skybox"
ChapterAdvancedOpengl15 = "6.2.cubemaps_environment_mapping"
ChapterAdvancedOpengl16 = "8.advanced_glsl_ubo"
ChapterAdvancedOpengl17 = "9.1.geometry_shader_houses"
ChapterAdvancedOpengl18 = "9.2.geometry_shader_exploding"
ChapterAdvancedOpengl19 = "9.3.geometry_shader_normals"
)

const (
	ChapterAdvancedLighting1 = "1.advanced_lighting"
ChapterAdvancedLighting2 = "2.gamma_correction"
ChapterAdvancedLighting3 = "3.1.1.shadow_mapping_depth"
ChapterAdvancedLighting4 = "3.1.2.shadow_mapping_base"
ChapterAdvancedLighting5 = "3.1.3.shadow_mapping"
ChapterAdvancedLighting6 = "3.2.1.point_shadows"
ChapterAdvancedLighting7 = "3.2.2.point_shadows_soft"
ChapterAdvancedLighting8 = "3.3.csm"
ChapterAdvancedLighting9 = "4.normal_mapping"
ChapterAdvancedLighting10 = "5.1.parallax_mapping"
ChapterAdvancedLighting11 = "5.2.steep_parallax_mapping"
ChapterAdvancedLighting12 = "5.3.parallax_occlusion_mapping"
ChapterAdvancedLighting13 = "6.hdr"
ChapterAdvancedLighting14 = "7.bloom"
ChapterAdvancedLighting15 = "8.1.deferred_shading"
ChapterAdvancedLighting16 = "8.2.deferred_shading_volumes"
ChapterAdvancedLighting17 = "9.ssao"
)

const (
	ChapterPbr1 = "1.1.lighting"
ChapterPbr2 = "1.2.lighting_textured"
ChapterPbr3 = "2.1.1.ibl_irradiance_conversion"
ChapterPbr4 = "2.1.2.ibl_irradiance"
ChapterPbr5 = "2.2.1.ibl_specular"
ChapterPbr6 = "2.2.2.ibl_specular_textured"
)

const (
	ChapterInPractice1 = "1.debugging"
ChapterInPractice2 = "3.2d_game"
	ChapterInPractice3 = "2.text_rendering"
)
